const negatives = {
  ptBr: [
    "com certeza nao",
    "contra",
    "de forma alguma",
    "de jeito nenhum",
    "de maneira nenhuma",
    "deplorável",
    "desaprovo",
    "desconfortável",
    "desconheco",
    "desconheço",
    "deselegante",
    "desfavorável",
    "desleal",
    "desprezo",
    "desprezível",
    "especificamente nao",
    "esquisito",
    "horrível",
    "improvavél",
    "indesejável",
    "infeliz",
    "infelizmente nao",
    "infelizmente",
    "jamais",
    "lastimável",
    "lento",
    "me recuso",
    "n/a",
    "nego",
    "nem pensar",
    "nenhuma",
    "nunca",
    "não aceito",
    "não aprovo",
    "não assumo",
    "não concordo",
    "não conheco",
    "não conheço",
    "não desejo",
    "não gosto",
    "não quero",
    "não vale a pena",
    "não",
    "odeio",
    "pouco provável",
    "pouco relevante",
    "recuso",
    "rejeito",
    "repulgnante",
    "terrível",
  ],
  en: [
    "I never",
    "I don’t",
    "no",
    "none",
    "never",
    "nope",
    "nothing",
    "I don't",
    "I am not",
    "I'm not",
    "Im not",
    "I do not",
    "not",
    "not really",
    "I did'nt",
    "N/a",
    "havent",
    "haven't",
    "have not",
    "avoid",
    "I lack",
    "we do not",
    "don't",
    "we don't",
    "do not",
    "dont know",
    "don't know",
    "NA",
    "dunno",
    "IDK",
    "🤷‍♂️",
    "I dont",
  ],
};
export default negatives;
