const positives = {
  ptBr: [
    "Confirmo",
    "Conheco",
    "a favor",
    "aceito",
    "conheço",
    "acho que sim",
    "as vezes",
    "assumo",
    "claro",
    "com certeza",
    "concordo com os termos",
    "concordo",
    "confirmo",
    "conheco",
    "conheço",
    "elegante",
    "estou de acordo",
    "eu concordo",
    "eu estou de acordo",
    "eu gosto",
    "eu sei",
    "eu vou",
    "favorável",
    "li e concordo",
    "li e estou de acordo",
    "muitas vezes",
    "presumo que sim",
    "provavelmente",
    "provável",
    "raramente",
    "rápido",
    "sem dúvidas",
    "sem dúvidas",
    "sempre",
    "sim",
    "sim",
    "pois não",
  ],
  en: ["yes", "shure", "I am", "cool", "best of luck", "I agree"],
};

export default positives;
// : only 1.81% of the respondents can associate tests with non-deterministic behaviour with the term "Flaky Test" and the most popular term between respondents is "Integration Test" (5%). 56.36% of the developers consider that the occurrence of non-deterministic tests in software projects is problematic, and 20.90% of the developers said that never dealt with non-deterministic tests.
