const positives = [
  "Confirmo",
  "Conheco",
  "a favor",
  "aceito",
  "conheço",
  "acho que sim",
  "as vezes",
  "assumo",
  "claro",
  "com certeza",
  "concordo com os termos",
  "concordo",
  "confirmo",
  "conheco",
  "conheço",
  "elegante",
  "estou de acordo",
  "eu concordo",
  "eu estou de acordo",
  "eu gosto",
  "eu sei",
  "eu vou",
  "favorável",
  "li e concordo",
  "li e estou de acordo",
  "muitas vezes",
  "presumo que sim",
  "provavelmente",
  "provável",
  "raramente",
  "rápido",
  "sem dúvidas",
  "sem dúvidas",
  "sempre",
  "sim",
  "sim",
];

export default positives;
